### ISSUE TITLE
Add support for PR `reopened` events

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#16]
As discovered in #15, deploy previews are only created when a PR is first opened.

Support for generating previews when a PR is reopened could be added to improve the usability of this action. 

This can be potentially be done by changing the following: https://github.com/bakerkretzmar/laravel-deploy-preview/blob/7bbb6ac7683eeed678f12b7e3ca8cc45ff693c3f/src/index.ts#L36 

To: 
```typescript
if (pr.action === 'opened' || pr.action === "reopened") {
```

**Comment by bakerkretzmar** [comment]
Yeah this makes sense, if the site is destroyed when the PR is closed then `opened` and `reopened` can basically be treated the same way.
