### ISSUE TITLE
Add PR comment with preview URL

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#17]
Similar to Cloudflare pages, the functionality to add a comment to the given PR with a preview url would be a nice to have:

![image](https://github.com/bakerkretzmar/laravel-deploy-preview/assets/32590246/c87d8dd1-69bd-4ac4-b963-085367ab6c9e)

**Comment by bakerkretzmar** [comment]
Agreed this would be nice! Currently it just comments the URL but something like that screenshot would be better.

**Comment by GlitchWitch** [comment]
Ah, I am not seeing any comment currently. Perhaps related to #19

**Comment by GlitchWitch** [comment]
Ah, my bad. They weren't showing up for me because of #19
