### ISSUE TITLE
Add support for custom SSL certificates

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#18]
In certain dev environments that are not publicly accessible, let's encrypt will fail to connect to the server and issue a certificate. This causes both an error on forge, the error #19, and the inability to access the site.

To resolve this, an option to use or clone an existing certificate could be added the same way that it's available in the Forge UI.

![image](https://github.com/bakerkretzmar/laravel-deploy-preview/assets/32590246/931df98d-d5f8-430a-8724-3851b28ee8b4)

**Comment by GlitchWitch** [comment]
Perhaps the following variables would make sense:

> #### `existing-certificate` & `existing-certificate-key`
> 
> The `existing-certificate` and `existing-certificate-key` input parameters allow you to append set a custom certificate rather then getting a new one from let's encrypt
> 
> Example:
> 
> ```yaml
> - uses: bakerkretzmar/laravel-deploy-preview@v2
>   with:
>     forge-token: ${{ secrets.FORGE_TOKEN }}
>     servers: |
>       qa-1.acme.dev 60041
>     existing-certificate: |
>       ${{ secrets.SSL-CERTIFICATE}}
>     existing-certificate-key: |
>       ${{ secrets.SSL-PRIVATE-KEY }}
> 
> ```
> #### `clone-certificate`
> 
> The `clone-certificate` input parameter allow you to append clone an existing sites certificate rather then getting a new one from let's encrypt. The input can be any other site ID within Forge.
> 
> Example:
> 
> ```yaml
> - uses: bakerkretzmar/laravel-deploy-preview@v2
>   with:
>     forge-token: ${{ secrets.FORGE_TOKEN }}
>     servers: |
>       qa-1.acme.dev 60041
>     clone-certificate: 90051
> 
> ```

**Comment by bakerkretzmar** [comment]
Added in d12e80f72cf35294288cdbf63f3b0872f22b9244.
