### ISSUE TITLE
Add support for other database options

### ISSUE THREAD

**Issue by bakerkretzmar** [bakerkretzmar/laravel-deploy-preview#28]
We can't actually install a different database engine (e.g. Postgres instead of MySQL) because that option is only available at server creation, but we could allow skipping creation of a database or using SQLite.

**Comment by TzviPM** [comment]
skipping database creation would be awesome. Also, an example in the README for how to supply custom db info via `environment` would be nice. Happy to help however I can

**Comment by bakerkretzmar** [comment]
By 'custom' do you mean like a hosted one somewhere? You can put any environment variables you want in `environment`, including `DB_HOST`, `DB_DATABASE`, `DB_PORT`, etc.
