### ISSUE TITLE
Add support for github action outputs

### ISSUE THREAD

**Issue by TzviPM** [bakerkretzmar/laravel-deploy-preview#31]
Sites that have more complex requirements could make use of other github actions in a workflow / pipeline if `laravel-deploy-preview` provided the site id and url as an action output.

**Comment by naciriii** [comment]
Makes sense also to add deleted site id  to outputs on delete

**Comment by bakerkretzmar** [comment]
> Makes sense also to add deleted site id to outputs on delete

Done 👍🏻
