### ISSUE TITLE
Feature Request: Set Notification Settings For Site

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#42]
## Problem
Forge provides a useful set of notification settings for each site, including "Deployment Failure Emails", "Deployment Webhooks", and "Slack Deployment Notifications". 

![image](https://github.com/bakerkretzmar/laravel-deploy-preview/assets/32590246/863d153d-81b9-4619-b371-279025d3bd59)

However there is no way to set these for generated deploy-preview sites.

## Solution
It would be nice to have configuration options for each of these settings.

**Comment by bakerkretzmar** [comment]
Great idea 👍🏻

**Comment by bakerkretzmar** [comment]
The Forge API only lets you add webhooks currently, not email or Slack or any of the others. Webhook support is included now, and I emailed Forge support about it and they said the other stuff is in their backlog and should be built out and released at some point, so when they add it I'll support those too.

**Comment by DanielCoulbourne** [comment]
So it would be nice to be able to configure, ideally on a site level, but ideally on a server level, the deployment failure email. address.

We are sending a request to configure the site, it would be nice to be able to include an email here, or have another endpoint to hit to change it after site creation:

https://github.com/bakerkretzmar/laravel-deploy-preview/blob/23c1fa5c61dd6fbe0dd6e6215ab90a140d0a931d/src/forge.ts#L80-L110

**Comment by jbrooksuk** [comment]
We've just shipped a change to Forge that makes it possible to set the deployment failure emails; https://forge.laravel.com/api-documentation#deployment-failure-emails

**Comment by GlitchWitch** [comment]
> We've just shipped a change to Forge that makes it possible to set the deployment failure emails; https://forge.laravel.com/api-documentation#deployment-failure-emails

Shout out to the Laravel community, love to see it. Thanks for getting this flagged @DanielCoulbourne and for the update @jbrooksuk!

**Comment by GlitchWitch** [comment]
Can confirm this is now working for us as of v2.7.2 :tada:
