### ISSUE TITLE
Workflow fails if PHP Version is undefined

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#49]
As of #44 it seems that the workflow now always includes the PHP version in the `POST` request regardless of it is set.

This causes site creation to fail if a PHP version is not defined in the workflow file, despite the variable not being required.

(This issue was originally flagged by @noahc3)

**Comment by GlitchWitch** [comment]
WIP PR in #48

**Comment by bakerkretzmar** [comment]
Should be fixed in v2.7.1, thanks! Forge must have turned off the empty strings to null middleware or something because I think we've always been sending this empty string.

**Comment by GlitchWitch** [comment]
Thanks @bakerkretzmar, I believe we are still running into the secondary issue I mentioned. Myself, @noahc3, and @DanielCoulbourne were unable to determine the cause of the 404 issue that presented when using branch from #48 or setting the PHP version manually.

**Comment by bakerkretzmar** [comment]
Hmm. Were you including the PHP version in the format `php##`, like `php83`? And it's a PHP version that is already installed on the server?

**Comment by noahc3** [comment]
Posted details in #50 to keep things organized :)
